<a href="https://colab.research.google.com/github/KaueAbbe/Desigualdade_Educacional/blob/main/Desigualdade_Educacional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color = 'green' size = 7> Desigualdade Educacional</font>

**Resumo:**

Os dados usados nesse notebook tem origem em:
1. [Inequality in Education Around the Workd](https://www.kaggle.com/datasets/iamsouravbanerjee/inequality-in-education-around-the-world)

# Importar dados e Bibliotecas

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('/content/drive/MyDrive/Data Science/Projeto - Desigualdade/Inequality in Education.csv')
dados.head()

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Inequality in Education (2010),Inequality in Education (2011),Inequality in Education (2012),Inequality in Education (2013),Inequality in Education (2014),Inequality in Education (2015),Inequality in Education (2016),Inequality in Education (2017),Inequality in Education (2018),Inequality in Education (2019),Inequality in Education (2020),Inequality in Education (2021)
0,AFG,Afghanistan,Low,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,High,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Very High,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Very High,AS,26.0,NaN,NaN,NaN,NaN,NaN,NaN,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

# Explorar a Base de Dados e Tratar

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ISO3                            195 non-null    object
 1   Country                         195 non-null    object
 2   Human Development Groups        191 non-null    object
 3   UNDP Developing Regions         151 non-null    object
 4   HDI Rank (2021)                 191 non-null    float64
 5   Inequality in Education (2010)  137 non-null    float64
 6   Inequality in Education (2011)  150 non-null    float64
 7   Inequality in Education (2012)  157 non-null    float64
 8   Inequality in Education (2013)  165 non-null    float64
 9   Inequality in Education (2014)  168 non-null    float64
 10  Inequality in Education (2015)  168 non-null    float64
 11  Inequality in Education (2016)  168 non-null    float64
 12  Inequality in Education (2017)  168 non-null    float64
 13  Inequality in Education (2018)  172 non-null    float64
 14  Inequality in Education (2019)  174 non-null    float64
 15  Inequality in Education (2020)  176 non-null    float64
 16  Inequality in Education (2021)  176 non-null    float64
dtypes: float64(13), object(4)
memory usage: 26.0+ KB

Existem valores nulhos em quase todas as colunas. Quando for avaliar por colunas categóricas tomar cuidado com os valores nulos.

In [ ]:
dados.describe()

,HDI Rank (2021),Inequality in Education (2010),Inequality in Education (2011),Inequality in Education (2012),Inequality in Education (2013),Inequality in Education (2014),Inequality in Education (2015),Inequality in Education (2016),Inequality in Education (2017),Inequality in Education (2018),Inequality in Education (2019),Inequality in Education (2020),Inequality in Education (2021)
count,191.000000,137.000000,150.000000,157.000000,165.000000,168.000000,168.000000,168.000000,168.000000,172.000000,174.000000,176.000000,176.000000
mean,95.811518,20.654419,19.991823,19.473658,19.258472,19.135457,19.133751,18.853851,18.649140,18.396401,18.212993,18.006314,18.006314
std,55.307333,14.392552,14.342499,14.305732,14.470344,14.350759,14.475000,14.479261,14.558072,14.546446,14.553003,14.569313,14.569313
min,1.000000,1.322970,1.385640,1.390450,0.779397,0.765510,0.757375,0.724854,0.724854,0.550110,0.550110,0.550110,0.550110
25%,48.500000,6.917102,6.119250,6.011760,5.605950,6.127907,6.209205,6.130745,5.591175,5.854422,5.618515,5.518733,5.518733
50%,96.000000,17.825000,17.312742,16.421150,16.060770,15.957630,15.344075,14.461598,14.292875,13.565415,13.263530,12.843558,12.843558
75%,143.500000,30.542861,30.176057,30.201410,30.542861,30.564901,29.686837,29.647365,29.647365,29.326065,29.303075,28.335352,28.335352
max,191.000000,48.723000,48.723000,48.723000,49.321290,49.321290,49.321290,49.321290,49.321290,50.124110,50.124110,50.124110,50.124110

Percepções:
1. A média de todos diminuiu ao passar dos anos.
2. O desvio padrão teve baixo aumento.
3. Existem valores mínimos bem baixos, e que também diminuiu.
4. Os valores máximos aumentaram.

## Tratamento

### Traduzir Colunas

In [ ]:
for i, y in enumerate(dados.columns[5:]):
  dados = dados.rename(columns = {y:'taxa ' + str(2010 + i)})
  print(i, y)
dados.head()

0 Inequality in Education (2010)
1 Inequality in Education (2011)
2 Inequality in Education (2012)
3 Inequality in Education (2013)
4 Inequality in Education (2014)
5 Inequality in Education (2015)
6 Inequality in Education (2016)
7 Inequality in Education (2017)
8 Inequality in Education (2018)
9 Inequality in Education (2019)
10 Inequality in Education (2020)
11 Inequality in Education (2021)

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
0,AFG,Afghanistan,Low,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,High,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Very High,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Very High,AS,26.0,NaN,NaN,NaN,NaN,NaN,NaN,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

In [ ]:
dados = dados.rename(columns = {'Country':'paises',
                                'HDI Rank (2021)':'IDH(2021)',
                                'UNDP DEveloping Regions': 'regioes'})
dados.head()

,ISO3,paises,Human Development Groups,UNDP Developing Regions,IDH(2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
0,AFG,Afghanistan,Low,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,High,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Very High,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Very High,AS,26.0,NaN,NaN,NaN,NaN,NaN,NaN,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

In [ ]:
dados.iloc[:, 4]

0      180.0
1      148.0
2       67.0
3       40.0
4       26.0
       ...
190    111.0
191    183.0
192    109.0
193    154.0
194    146.0
Name: IDH(2021), Length: 195, dtype: float64

In [ ]:
for i, col in enumerate(dados):
  if i <5:
    dados.iloc[:, i] = dados.iloc[:, i]
  else:
    dados.iloc[:, i] = dados.iloc[:, i].fillna(value = dados[['taxa ' + str(x) for x in range(2010, 2022)]].mean(axis = 1), )
dados.head()

,ISO3,paises,Human Development Groups,UNDP Developing Regions,IDH(2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
0,AFG,Afghanistan,Low,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Medium,SSA,148.0,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,High,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Very High,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Very High,AS,26.0,13.875699,13.875699,13.875699,13.875699,13.875699,13.875699,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ISO3                      195 non-null    object
 1   paises                    195 non-null    object
 2   Human Development Groups  191 non-null    object
 3   UNDP Developing Regions   151 non-null    object
 4   IDH(2021)                 191 non-null    float64
 5   taxa 2010                 182 non-null    float64
 6   taxa 2011                 182 non-null    float64
 7   taxa 2012                 182 non-null    float64
 8   taxa 2013                 182 non-null    float64
 9   taxa 2014                 182 non-null    float64
 10  taxa 2015                 182 non-null    float64
 11  taxa 2016                 182 non-null    float64
 12  taxa 2017                 182 non-null    float64
 13  taxa 2018                 182 non-null    float64
 14  taxa 2019                 182 non-null    float64
 15  taxa 2020                 182 non-null    float64
 16  taxa 2021                 182 non-null    float64
dtypes: float64(13), object(4)
memory usage: 26.0+ KB

In [ ]:
dados[dados['taxa 2010'].isna()]

,ISO3,paises,Human Development Groups,UNDP Developing Regions,IDH(2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
7,ATG,Antigua and Barbuda,High,LAC,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BRN,Brunei,Very High,EAP,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,DMA,Dominica,High,LAC,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,ERI,Eritrea,Low,SSA,176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,FSM,Micronesia,Medium,EAP,134.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,GNQ,Equatorial Guinea,Medium,SSA,145.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,GRD,Grenada,High,LAC,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,KNA,Saint Kitts and Nevis,High,LAC,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,LBY,Libya,High,AS,104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,LIE,Liechtenstein,Very High,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,MCO,Monaco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,NRU,Nauru,NaN,EAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,PRK,North Korea,NaN,EAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dados_tratados = dados.dropna(subset = ['taxa ' + str(x) for x in range(2010, 2022)]).copy()

In [ ]:
dados_tratados.head()

,ISO3,paises,Human Development Groups,UNDP Developing Regions,IDH(2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
0,AFG,Afghanistan,Low,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Medium,SSA,148.0,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,High,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Very High,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Very High,AS,26.0,13.875699,13.875699,13.875699,13.875699,13.875699,13.875699,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

###Tradução

In [ ]:
dados_tratados['Human Development Groups'].unique()

array(['Low', 'Medium', 'High', 'Very High', nan], dtype=object)

In [ ]:
dados_tratados = dados_tratados.replace({'Low':'Baixa', 'Medium':'Media','High':'Alta','Very High': 'Muito Alta', 43.51879: np.nan})

In [ ]:
dados_tratados

,ISO3,paises,Human Development Groups,UNDP Developing Regions,IDH(2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
0,AFG,Afghanistan,Baixa,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Media,SSA,148.0,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,Alta,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Muito Alta,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Muito Alta,AS,26.0,13.875699,13.875699,13.875699,13.875699,13.875699,13.875699,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,WSM,Samoa,Alta,EAP,111.0,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960,7.029960
191,YEM,Yemen,Baixa,AS,183.0,48.090120,48.090120,48.090120,46.137650,46.137650,46.137650,46.137650,46.137650,46.137650,46.137650,46.137650,46.137650
192,ZAF,South Africa,Alta,SSA,109.0,16.621268,16.621268,16.060770,16.060770,16.060770,14.265590,17.294130,17.294130,17.294130,17.294130,17.294130,17.294130
193,ZMB,Zambia,Media,SSA,154.0,23.760000,23.760000,23.760000,23.760000,21.734910,21.734910,21.734910,21.734910,20.435720,20.435720,20.435720,20.435720
194,ZWE,Zimbabwe,Media,SSA,146.0,17.825000,17.825000,17.825000,17.825000,17.395210,16.805760,16.805760,16.805760,16.805760,14.605030,14.605030,14.605030

In [ ]:
dados_tratados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182 entries, 0 to 194
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ISO3                      182 non-null    object
 1   paises                    182 non-null    object
 2   Human Development Groups  181 non-null    object
 3   UNDP Developing Regions   140 non-null    object
 4   IDH(2021)                 181 non-null    float64
 5   taxa 2010                 181 non-null    float64
 6   taxa 2011                 181 non-null    float64
 7   taxa 2012                 181 non-null    float64
 8   taxa 2013                 181 non-null    float64
 9   taxa 2014                 181 non-null    float64
 10  taxa 2015                 181 non-null    float64
 11  taxa 2016                 181 non-null    float64
 12  taxa 2017                 181 non-null    float64
 13  taxa 2018                 181 non-null    float64
 14  taxa 2019                 181 non-null    float64
 15  taxa 2020                 182 non-null    float64
 16  taxa 2021                 182 non-null    float64
dtypes: float64(13), object(4)
memory usage: 25.6+ KB

In [ ]:
dados_tratados  = dados_tratados.reindex([x for x in range(0, 182)])

In [ ]:
dados_tratados.to_csv('/content/drive/MyDrive/Data Science/Projeto - Desigualdade/Desigualdade_tratado.csv', index = False)


# Análise Exploratória.

## 1. A média do planeta

In [ ]:
dados = pd.read_csv('/content/drive/MyDrive/Data Science/Projeto - Desigualdade/Desigualdade_tratado.csv')

In [ ]:
media_mundo = dados.describe().loc['mean']
media_mundo[1:].values

array([19.76239158, 19.58965504, 19.44671841, 19.26108974, 19.24007504,
       19.035064  , 18.8252735 , 18.62483976, 18.33456839, 18.2981748 ,
       18.34252999, 18.34252999])

In [ ]:
anos = [x for x in range(2010, 2022)]
anos

[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [ ]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px

In [ ]:
def graf_linha(x, y, titulo, xlabel, ylabel):
  fig = px.line(x = x, y =y )

  fig.update_xaxes(title_text= xlabel, row=1, col=1, showgrid = False,showline=True)
  fig.update_yaxes(title_text=ylabel, row=1, col=1,showgrid = False,showline=True)
  fig.update_xaxes(showline=True, linewidth=2, linecolor='black')
  fig.update_yaxes(showline=True, linewidth=2, linecolor='black')

  fig.update_layout(showlegend=False, plot_bgcolor="white",title_text=titulo)



  fig.show()

graf_linha(anos, media_mundo[1:].values, 'Desigualdade Média do Mundo', 'Anos','Desigualdade')

## Desvio Padrão

In [ ]:
std_mundo = dados.describe().loc['std']

graf_linha(anos, std_mundo[1:].values, 'Desvio Padrão Desigualdade do Mundo', 'Anos','Desvio Padrão')

## Mínimo e o Máximo

In [ ]:
valoresY= dados.describe().loc['min']

graf_linha(anos, valoresY[1:].values, 'Mínimos de Desigualdade do Mundo', 'Anos','Minimo')

In [ ]:
valoresY= dados.describe().loc['max']

graf_linha(anos, valoresY[1:].values, 'Máximo de Desigualdade do Mundo', 'Anos','Maximo')

* Mesma conclusão: Enquanto a média diminuiu teve países que aumentam o valor máximo de desigualdade, e países que diminuiram o valor mínimo. Em média a desigualdade diminuiu

Perguntas:
1. Quais são os 5 países e Regiões com Maiores números de desigualdade no último ano?
2. Quais sãos os 5 países e Regiões com menores números de desiguldade no último ano?

## Regiões com Maiores Números de Desigualdade

In [ ]:
dados.head()

,ISO3,paises,Human Development Groups,UNDP Developing Regions,IDH(2021),taxa 2010,taxa 2011,taxa 2012,taxa 2013,taxa 2014,taxa 2015,taxa 2016,taxa 2017,taxa 2018,taxa 2019,taxa 2020,taxa 2021
0,AFG,Afghanistan,Baixa,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Media,SSA,148.0,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,Alta,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Muito Alta,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Muito Alta,AS,26.0,13.875699,13.875699,13.875699,13.875699,13.875699,13.875699,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

In [ ]:
dados_por_regioes = dados.copy()

In [ ]:
dados_por_regioes[~dados_por_regioes.isna()['Inequality in Education (2021)']].info()

KeyError: ignored

In [ ]:
dados_por_regioes = dados_por_regioes[~dados_por_regioes.isna()['Inequality in Education (2021)']]
dados_por_regioes

KeyError: ignored

In [ ]:
group_regioes = dados_por_regioes.groupby('UNDP Developing Regions').apply('mean')
group_regioes

<ipython-input-80-0a5093a1f6e8>:1: FutureWarning:

The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.

,HDI Rank (2021),Inequality in Education (2010),Inequality in Education (2011),Inequality in Education (2012),Inequality in Education (2013),Inequality in Education (2014),Inequality in Education (2015),Inequality in Education (2016),Inequality in Education (2017),Inequality in Education (2018),Inequality in Education (2019),Inequality in Education (2020),Inequality in Education (2021)
UNDP Developing Regions,,,,,,,,,,,,,
AS,90.375000,31.193586,27.563814,27.000721,26.458268,26.303613,24.901950,23.988050,23.420237,23.921208,23.895774,23.895774,23.895774
EAP,108.450000,19.522350,17.725928,17.873842,16.655654,16.613274,16.859012,18.087029,17.676001,17.204483,16.502628,15.543478,15.543478
ECA,77.823529,9.473114,8.319860,7.408935,7.034473,7.054572,6.912564,6.292867,6.280969,5.895637,5.806496,5.790199,5.790199
LAC,94.928571,18.937781,18.044010,17.183198,16.983504,16.544730,16.380586,15.960976,15.381143,15.262223,15.137601,15.127795,15.127795
SA,123.444444,37.769162,37.775392,37.775255,37.665671,37.823176,37.421866,33.081499,33.364202,33.169510,33.189693,33.189693,33.189693
SSA,157.727273,33.737580,33.780130,33.552165,33.890120,33.890472,33.769185,33.794198,33.751455,33.519001,32.899649,32.887848,32.887848

In [ ]:
regioes = group_regioes.sort_values(by = 'Inequality in Education (2021)').index
regioes

Index(['ECA', 'LAC', 'EAP', 'AS', 'SSA', 'SA'], dtype='object', name='UNDP Developing Regions')

In [ ]:
regioes_2021 = group_regioes.sort_values(by = 'Inequality in Education (2021)')['Inequality in Education (2021)'].values
regioes_2021

array([ 5.79019892, 15.12779517, 15.54347765, 23.8957744 , 32.88784769,
       33.18969264])

In [ ]:
def graf_bar(x, y, titulo, xlabel, ylabel):
  fig = px.bar(x = x, y =y )

  fig.update_xaxes(title_text= xlabel, row=1, col=1, showgrid = False,showline=True)
  fig.update_yaxes(title_text=ylabel, row=1, col=1,showgrid = False,showline=True)
  fig.update_xaxes(showline=True, linewidth=2, linecolor='black')
  fig.update_yaxes(showline=True, linewidth=2, linecolor='black')

  fig.update_layout(showlegend=False, plot_bgcolor="white",title_text=titulo)



  fig.show()

graf_bar(regioes, regioes_2021,"Desiguldade por região em 2021", "Regiões", "Desiguldade")

## Por País maior e menor desigualdade em 2021

In [ ]:
dados.head()

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Inequality in Education (2010),Inequality in Education (2011),Inequality in Education (2012),Inequality in Education (2013),Inequality in Education (2014),Inequality in Education (2015),Inequality in Education (2016),Inequality in Education (2017),Inequality in Education (2018),Inequality in Education (2019),Inequality in Education (2020),Inequality in Education (2021)
0,AFG,Afghanistan,Low,SA,180.0,42.809000,44.823380,44.823380,44.823380,44.823380,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170,45.365170
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440,34.171440
2,ALB,Albania,High,ECA,67.0,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,11.900000,12.333440,12.333440,12.333440,12.333440,12.333440
3,AND,Andorra,Very High,NaN,40.0,15.160302,15.160302,15.160302,15.160302,9.965681,10.083815,10.008154,10.008154,10.008154,10.008154,10.008154,10.008154
4,ARE,United Arab Emirates,Very High,AS,26.0,NaN,NaN,NaN,NaN,NaN,NaN,18.241437,14.475335,12.634355,12.634355,12.634355,12.634355

In [ ]:
dados_por_paises = dados_por_regioes.sort_values(by = 'Inequality in Education (2021)').copy()

In [ ]:
dados_por_paises.tail()

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Inequality in Education (2010),Inequality in Education (2011),Inequality in Education (2012),Inequality in Education (2013),Inequality in Education (2014),Inequality in Education (2015),Inequality in Education (2016),Inequality in Education (2017),Inequality in Education (2018),Inequality in Education (2019),Inequality in Education (2020),Inequality in Education (2021)
152,SEN,Senegal,Low,SSA,170.0,44.57900,44.57900,44.57900,44.22756,44.74737,45.28813,46.45389,45.988460,46.364120,47.135300,47.135300,47.135300
155,SLE,Sierra Leone,Low,SSA,181.0,48.72300,48.72300,48.72300,47.29928,47.29928,47.29928,47.29928,46.926770,46.926770,47.502890,47.502890,47.502890
38,COM,Comoros,Medium,SSA,156.0,NaN,NaN,47.61438,47.61438,47.61438,47.61438,47.61438,47.614380,47.614380,47.614380,47.614380,47.614380
26,BTN,Bhutan,Medium,SA,127.0,44.81067,44.81067,44.81067,44.81067,44.81067,44.81067,44.81067,48.226575,48.226575,48.226575,48.226575,48.226575
64,GIN,Guinea,Low,SSA,182.0,42.00000,42.00000,48.26536,48.26536,48.26536,48.26536,48.26536,48.265360,50.124110,50.124110,50.124110,50.124110

In [ ]:
paises_top_desiguais = dados_por_paises.tail()['Country'].values
paises_top_desiguais_valores = dados_por_paises.tail()['Inequality in Education (2021)'].values

graf_bar(paises_top_desiguais, paises_top_desiguais_valores,"Paises com Maiores Desigualdades em 2021", "Países", "Desiguldade")

In [ ]:
dados_por_paises.head()

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Inequality in Education (2010),Inequality in Education (2011),Inequality in Education (2012),Inequality in Education (2013),Inequality in Education (2014),Inequality in Education (2015),Inequality in Education (2016),Inequality in Education (2017),Inequality in Education (2018),Inequality in Education (2019),Inequality in Education (2020),Inequality in Education (2021)
185,UZB,Uzbekistan,High,ECA,101.0,NaN,NaN,NaN,0.779397,0.765510,0.757375,0.724854,0.724854,0.550110,0.550110,0.550110,0.550110
43,CZE,Czechia,Very High,NaN,32.0,1.322970,1.385640,1.390450,1.372730,1.613200,1.529440,1.600350,1.377010,1.388240,1.388240,1.255630,1.255630
163,SVK,Slovakia,Very High,NaN,45.0,1.505540,1.538320,1.537670,1.404980,1.632760,1.414000,1.438040,1.556130,1.556130,1.556130,1.747920,1.747920
133,NZL,New Zealand,Very High,NaN,13.0,1.568288,1.817446,1.809829,1.809829,1.810199,1.772488,1.840132,1.840132,1.840132,1.840132,1.840132,1.840132
30,CHE,Switzerland,Very High,NaN,1.0,NaN,NaN,NaN,2.348090,2.378520,2.366899,1.931140,1.931140,1.828790,1.828790,2.014570,2.014570

In [ ]:
paises_min_desiguais = dados_por_paises.head()['Country'].values
paises_min_desiguais_valores = dados_por_paises.head()['Inequality in Education (2021)'].values

graf_bar(paises_min_desiguais, paises_min_desiguais_valores,"Paises com Maiores Desigualdades em 2021", "Países", "Desiguldade")